[project]
name = "stock-sentiment"
version = "0.1.0"
description = "Stock sentiment analysis"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "xai-sdk>=1.5.0",
    "markdown",
    "pydantic",
    "click>=8.3.1",
    "jinja2>=3.1.6",
]
